id = "firefox-quantum-themes"
name = "Firefox Quantum Themes"
version = "1.0.2"
schema_version = 1
authors = ["beastdestroyer <https://github.com/beastdestroyer>", "chpxu https://github.com/chpxu", "devinaxo <https://github.com/devinaxo>"]
description = "A Zed port of the Firefox Quantum themes for Visual Studio Code, based on Firefox DevTools colors"
repository = "https://github.com/devinaxo/zed-firefox-quantum-themes"
